
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async errorPopup(msg: string) : Promise<void> {
    await TAURI_INVOKE("error_popup", { msg });
},
async loadLibrary(libraryJson: string) : Promise<Result<LibraryTauri, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_library", { libraryJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CountObject = { count: string; fromDate: string; toDate: string }
export type Folder = { id: string; name: string; description?: string | null; liked: boolean; disliked: boolean; 
/**
 * For example "itunes"
 */
importedFrom?: string | null; 
/**
 * For example iTunes Persistent ID
 */
originalId?: string | null; dateImported?: string | null; dateCreated?: string | null; children: string[] }
export type LibraryTauri = { tracks: Partial<{ [key in string]: Track }>; track_item_ids: Partial<{ [key in string]: number }>; track_lists: Partial<{ [key in string]: TrackList }> }
export type Playlist = { id: string; name: string; description?: string | null; liked: boolean; disliked: boolean; importedFrom?: string | null; originalId?: string | null; dateImported?: string | null; dateCreated?: string | null; tracks: number[] }
export type Special = { id: string; name: SpecialTrackListName; dateCreated: string; children: string[] }
export type SpecialTrackListName = "Root"
export type Track = { size: string; duration: number; bitrate: number; sampleRate: number; file: string; dateModified: string; dateAdded: string; name: string; importedFrom?: string | null; 
/**
 * Imported ID, like iTunes Persistent ID
 */
originalId?: string | null; artist?: string; composer?: string | null; sortName?: string | null; sortArtist?: string | null; sortComposer?: string | null; genre?: string | null; rating?: number | null; year?: string | null; bpm?: number | null; comments?: string | null; grouping?: string | null; liked?: boolean | null; disliked?: boolean | null; disabled?: boolean | null; compilation?: boolean | null; albumName?: string | null; albumArtist?: string | null; sortAlbumName?: string | null; sortAlbumArtist?: string | null; trackNum?: number | null; trackCount?: number | null; discNum?: number | null; discCount?: number | null; dateImported?: string | null; playCount?: number | null; plays?: string[] | null; playsImported?: CountObject[] | null; skipCount?: number | null; skips?: string[] | null; skipsImported?: CountObject[] | null; 
/**
 * -100 to 100
 */
volume?: number | null }
export type TrackList = ({ type: "playlist" } & Playlist) | ({ type: "folder" } & Folder) | ({ type: "special" } & Special)

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
